hosts:
  zookeeper_domain: zookeeper
  dbserver_domain: dbserver
nodes:
  zookeeper: 192.168.57.170
  nimbus: 192.168.57.169
  distributednode_manager: 192.168.57.169
  distributednode_presenterworker: 192.168.57.171
  distributednode_managerworker: 192.168.57.170
  distributednode_worker: 192.168.57.172
  distributednode_presenter: 192.168.57.173
  dbserver: 192.168.57.170